config/routes.rb
Typing::Application.routes.draw do
  
  devise_for :users
  root :to => "users#home"

  resources :users, :only => [:index]

  resources :types

end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :types
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!, except: [:home]
    
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def index
    @types = Type.order("created_at DESC")
  end

  def show
    @type = Type.find(params[:id])
  end

  def new
    @type = Type.new
  end

  def create
    type = Type.create(params[:type])
    type.user = current_user
    type.save
    redirect_to types_path(type.id)
  end

  def edit
    @type = Type.find(params[:id])
  end

  def update
    type = Type.find(params[:id])
    type.update_attributes(params[:type])
    redirect_to type_path(type)
  end

  def destroy
    Type.destroy(params[:id])
    redirect_to types_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Typing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Fauna+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
</head>

  <header class="header_bar">

    <div class="nav-left">
      <% if user_signed_in? %>
        <ul>
          <li> <%= link_to "View All Sets", types_path %> </li>
          <li> <%= link_to "Make New Set", new_type_path %> </li>
        </ul>
      <% end %>
    </div>

    <div class= "nav-right">
      <ul>
      <% if user_signed_in? %>
        Logged in as <%= current_user.email %>. |
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
      </ul>
    </div>

  </header>

<body>

  <%= yield %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

</body>
</html>

app/views/types/edit.html.erb
<div class="container">

  <%= form_for @type do |f|%>
    <%= f.text_field :title %><br>
    <%= f.text_area :content, size: "70x30" %>
    <%= f.submit "Save Changes" %>
  <% end %>

</div>

app/views/types/index.html.erb
<div class="container">
  
  <table class="types-table">
    <tr> 
      <td>Title</td>
      <td> by</td>
      <td> made on</td>
      <td> edit</td>
      <td> delete</td>
    </tr>
    <% @types.each do |type| %>
      <tr> 
        <td><%= link_to type.title, type_path(type) %></td>
        <td><%= type.user.email %></td>
        <td><%= type.created_at %></td>
        <% if type.user.id == current_user.id %>
          <td><%= link_to "Edit", edit_type_path(type) %></td>
          <td><%= link_to "Delete", type_path(type), method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

</div>

app/views/types/new.html.erb
<div class="container">
  
  <%= form_for @type do |f|%>
    <%= f.text_field :title, placeholder: "Title" %><br>
    <%= f.text_area :content, size: "70x30", placeholder: "Enter your content here" %>
    <%= f.submit "Create" %>
  <% end %>
  
</div>

app/views/types/show.html.erb
<div class="container">
  
  <table border=1 class="type-header">
    <tr> 
      <td><%= @type.title %></td>
      <td><%= @type.created_at %></td>
      <td><%= @type.user.email %></td>
    </tr>
  </table>
  <div class="type-content">
    <p>
      <%= @type.content %>
    </p>
    <%= link_to "Edit", edit_type_path(@type) %> 
    <%= link_to "Delete", type_path(@type), method: :delete %> 
  </div>
  
</div>

app/views/users/home.html.erb
<div class="container">
  
  <h1>Hello!</h1>
  <%= link_to "secret", users_path %>

</div>

app/views/users/index.html.erb
<div class="container">
  
  <h1>You are viewing this if you're signed in</h1>

</div>